apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudnative-pv
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: "Filesystem"
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: cloudnative-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudnative-pvc
  namespace: default
spec:
  volumeName: cloudnative-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
